package ventanas;

import java.sql.*;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author maxco
 */
public class StudentRecordApp extends javax.swing.JFrame {

    /**
     * Creates new form RegistroAlumnos
     */
    public StudentRecordApp() {
        initComponents();
        setLocationRelativeTo(null);

        setSize(500, 390);
        setResizable(false);
        setTitle("College system");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/img/header.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(background.getWidth(),
                background.getHeight(), java.awt.Image.SCALE_DEFAULT));
        background.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGroup = new javax.swing.JTextField();
        bt_registrar = new javax.swing.JButton();
        bt_Editar = new javax.swing.JButton();
        bt_Eliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label_status = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setText("Student system");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        txtName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 159, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        jLabel2.setText("Created by Maximiliano Colque Jaunin ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 330, -1, -1));

        txtGroup.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(txtGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 78, -1));

        bt_registrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bt_registrar.setText("Save");
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        bt_Editar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bt_Editar.setText("Edit");
        bt_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EditarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        bt_Eliminar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bt_Eliminar.setText("Delete");
        bt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Student id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 17));

        txtId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 71, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        label_status.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_status.setForeground(new java.awt.Color(0, 153, 0));
        label_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_status.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 190, 30));

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Generate PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 160, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Group:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/college?useSSL=false", "root", "root");
            PreparedStatement pst = cn.prepareStatement("insert into student values(?,?,?)");

            pst.setString(1, "0");
            pst.setString(2, txtName.getText().trim());
            pst.setString(3, txtGroup.getText().trim());
            pst.executeUpdate();

            txtName.setText("");
            txtGroup.setText("");
            label_status.setText("Success record");
        } catch (SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_bt_registrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/college?useSSL=false", "root", "root");
            PreparedStatement pst = cn.prepareStatement("select * from student where ID = ? ");

            pst.setString(1, txtId.getText().trim());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtName.setText(rs.getString("name"));
                txtGroup.setText(rs.getString("group"));

            } else {
                JOptionPane.showMessageDialog(null, "Student did not find");
            }

        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EditarActionPerformed
        try {
            String ID = txtId.getText().trim();

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/college?useSSL=false", "root", "root");
            PreparedStatement pst = cn.prepareStatement("update student set name = ?, group = ? where ID = " + ID);

            pst.setString(1, txtName.getText().trim());
            pst.setString(2, txtGroup.getText().trim());
            pst.executeUpdate();

            label_status.setText("Successful update");
        } catch (Exception e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_bt_EditarActionPerformed

    private void bt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EliminarActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/college?useSSL=false", "root", "root");
            PreparedStatement pst = cn.prepareStatement("delete from student where ID = ?");

            pst.setString(1, txtId.getText().trim());
            pst.executeUpdate();

            txtName.setText("");
            txtGroup.setText("");
            txtId.setText("");

            label_status.setText("Successful delete");
        } catch (Exception e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_bt_EliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Document doc = new Document();
        try {
            String path = System.getProperty("user.home");
            PdfWriter.getInstance(doc, new FileOutputStream(path + "/Desktop/studentRecord.pdf"));

            Image header = Image.getInstance("src/img/header.png");
            header.scaleAbsolute(500, 50);
            header.getAbsoluteX();


            PdfPTable tabla = new PdfPTable(3);
            tabla.addCell("ID");
            tabla.addCell("Student name");
            tabla.addCell("Group");

            Paragraph paragraph = new Paragraph();
            paragraph.setAlignment(Paragraph.ALIGN_CENTER);
            paragraph.setFont(FontFactory.getFont("Arial", 22, Font.BOLD, BaseColor.BLACK));
            paragraph.add("Record student \n\n");

            doc.open();
            doc.add(header);
            doc.add(paragraph);

            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/college?useSSL=false", "root", "root");
                PreparedStatement pst = cn.prepareStatement("select * from student");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    do {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                    } while (rs.next());
                    doc.add(tabla);
                }

                doc.close();
                JOptionPane.showMessageDialog(null, "Reporte creado");
            } catch (DocumentException | HeadlessException | SQLException e) {
                System.err.println(e);
            }

        } catch (DocumentException | FileNotFoundException e) {
            System.err.println(e);

        } catch (IOException e) {
            System.err.println(e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRecordApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRecordApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRecordApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRecordApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRecordApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton bt_Editar;
    private javax.swing.JButton bt_Eliminar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label_status;
    private javax.swing.JTextField txtGroup;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
